# Generated by Django 2.2.26 on 2022-01-22 03:53

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тэг товар',
                'verbose_name_plural': 'Тэги товаров',
            },
        ),
        migrations.CreateModel(
            name='Сustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('сustomer_contacts', djongo.models.fields.EmbeddedField(blank=True, model_container=shop.models.СustomerContacts, null=True, verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.FloatField(blank=True, default=0, verbose_name='Цена')),
                ('count', models.IntegerField(blank=True, default=0, verbose_name='Количество товара на складе')),
                ('product_extra_fields', djongo.models.fields.ArrayField(blank=True, model_container=shop.models.ProductExtraField, model_form_class=shop.models.ProductExtraFieldForm)),
                ('product_category', djongo.models.fields.EmbeddedField(blank=True, model_container=shop.models.ProductCategory, null=True, verbose_name='Категория товара')),
                ('product_tags', djongo.models.fields.ArrayReferenceField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductTag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
